### ISSUE TITLE
Aircraft Throws Error When Generating Stat Cards

### ISSUE THREAD

**Issue by Soyvolon** [PyrrhicSteel/VORPointGenerator#18] opened 2024-10-02 22:27 UTC
After a fresh clone from github, generation of aircraft stat cards fails. This may be because the aircraft image locations are not pathed correctly (I don't have any files in my documents folder).

```
GENERATING AIRCRAFT STATCARDS...

Failed to write ship!
System.IO.DirectoryNotFoundException: The directory C:\Users\Soyvolon\OneDrive - My Job That You Don't Get To Know\Documents\My Games\Valkyries of Ran\Aircraft\USA Multirole Carrier Jet Fighter F of the filename C:\Users\Soyvolon\OneDrive - My Job That You Don't Get To Know\Documents\My Games\Valkyries of Ran\Aircraft\USA Multirole Carrier Jet Fighter F/A-18F Super Hornet.jpeg does not exist.
   at System.Drawing.Image.ThrowIfDirectoryDoesntExist(String filename)
   at System.Drawing.Image.Save(String filename, ImageCodecInfo encoder, EncoderParameters encoderParams)
   at VORPointGenerator.aircraftStats.generateStatCard(String name, String countryOfOrigin, String cameo, String artist, String artLink) in C:\Users\Soyvolon\Source\Repos\VORPointGenerator\VORPointGenerator\aircraftStats.cs:line 608
Failed to write ship!
System.IO.DirectoryNotFoundException: The directory C:\Users\Soyvolon\OneDrive - My Job That You Don't Get To Know\Documents\My Games\Valkyries of Ran\Aircraft\USA Multirole Carrier Jet Fighter F of the filename C:\Users\Soyvolon\OneDrive - My Job That You Don't Get To Know\Documents\My Games\Valkyries of Ran\Aircraft\USA Multirole Carrier Jet Fighter F/A-18E Super Hornet.jpeg does not exist.
   at System.Drawing.Image.ThrowIfDirectoryDoesntExist(String filename)
   at System.Drawing.Image.Save(String filename, ImageCodecInfo encoder, EncoderParameters encoderParams)
   at VORPointGenerator.aircraftStats.generateStatCard(String name, String countryOfOrigin, String cameo, String artist, String artLink) in C:\Users\Soyvolon\Source\Repos\VORPointGenerator\VORPointGenerator\aircraftStats.cs:line 608
```

**Comment by PyrrhicSteel** [comment] 2024-10-02 23:07
This should be fixed now. The issue is probably due to '/' being a forbidden character for files in Linux/Unix systems, while it is permitted in Windows based systems. Aircraft and ship names should be sanitized before getting added to the file now.

**Closed** 2024-10-02 23:47 UTC
Labels: bug
